# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem 'rake'
  gem 'yard'
  gem 'rspec', '~> 3.0'
  gem 'rspec-power_assert', '~> 1.1'
end
