require 'rspec/core/rake_task'
require 'yard'
require 'yard/rake/yardoc_task'

task :default => [:spec]

YARD::Rake::YardocTask.new do |task|
  task.options = []
end

RSpec::Core::RakeTask.new(:spec)
