# This is a basic workflow to help you get started with Actions

name: LaTeX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    # Runs only newly opend or pushed updating commit (NOT reopened)
    # ref : https://qiita.com/osakiy/items/27d5382e41107de482a4
    types: [opened, synchronize]
    paths: '**.tex'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Checkout constitution
      - name: Clone constitution
        uses: actions/checkout@v2
        with:
          repository: ritscc/constitution
          path: constitution
          token: ${{ secrets.ACCESS_TOKEN }}

      # Checkout tex-commands
      - name: Clone tex-commands
        uses: actions/checkout@v2
        with:
          repository: ritscc/tex-commands
          path: tex-commands
          token: ${{ secrets.ACCESS_TOKEN }}

      # Build TeX documents
      - name: TeX Build
        uses: ./.github/actions/latex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
